#!/bin/bash

CHANGELOG_HEADER="`head -n1 debian/changelog`"
PACKAGE=`echo $CHANGELOG_HEADER | sed -e "s/(.*//" -e "s/ //g"`
UPSTREAM_VERSION=`echo $CHANGELOG_HEADER | sed -e "s/[a-zA-Z0-9 \-]*(//" -e "s/).*//" -e "s/[0-9]*$//" -e "s/ //g" -e "s/^[0-9]*://" -e "s/-[^ ]*$//g"`

echo "######################################################################"
echo "CHANGELOG_HEADER:   $CHANGELOG_HEADER"
echo "PACKAGE:            $PACKAGE"
echo "UPSTREAM_VERSION:   $UPSTREAM_VERSION"
echo "######################################################################"

. ./debian.conf

CHANGELOG_HEADER="`head -n1 debian/changelog`"
PACKAGE=`echo $CHANGELOG_HEADER | sed -e "s/(.*//" -e "s/ //g"`

if [ -e $PACKAGE-$UPSTREAM_VERSION ] ; then
   rm -rf $PACKAGE-$UPSTREAM_VERSION
fi
mkdir $PACKAGE-$UPSTREAM_VERSION || exit 1
# ( qtchooser -qt=5 -run-tool=qmake && make clean) || exit 1

# ---------------------------------------------------------
mkdir $PACKAGE-$UPSTREAM_VERSION/src
mkdir $PACKAGE-$UPSTREAM_VERSION/src/examples
cp NEWS README BUGS COPYING ChangeLog *.lsm $PACKAGE-$UPSTREAM_VERSION
cp *.pro $PACKAGE-$UPSTREAM_VERSION
cp src/*.pro $PACKAGE-$UPSTREAM_VERSION/src
cp src/*.cpp $PACKAGE-$UPSTREAM_VERSION/src
cp src/*.h   $PACKAGE-$UPSTREAM_VERSION/src
cp src/examples/*.fsf $PACKAGE-$UPSTREAM_VERSION/src/examples
find $PACKAGE-$UPSTREAM_VERSION/src -name "moc_*" | xargs rm -f
# ---------------------------------------------------------

tar czvf $PACKAGE-$UPSTREAM_VERSION.tar.gz $PACKAGE-$UPSTREAM_VERSION
rm -rf $PACKAGE-$UPSTREAM_VERSION
