#!/bin/bash

VERSION=2.0.4

. ./debian.conf
if [ -e $PACKAGE-$VERSION ] ; then
   rm -rf $PACKAGE-$VERSION
fi
mkdir $PACKAGE-$VERSION || exit 1
# ( qmake-qt4 && make clean) || exit 1

# ---------------------------------------------------------
mkdir $PACKAGE-$VERSION/src
cp *.pro $PACKAGE-$VERSION
cp src/*.pro $PACKAGE-$VERSION/src
cp src/*.cpp $PACKAGE-$VERSION/src
cp src/*.h   $PACKAGE-$VERSION/src
find $PACKAGE-$VERSION/src -name "moc_*" | xargs rm -f
# ---------------------------------------------------------

tar czvf $PACKAGE-$VERSION.tar.gz $PACKAGE-$VERSION
rm -rf $PACKAGE-$VERSION
