.\" $Id$
.\"
.\" Fractal Generator
.\" Copyright (C) 2003-2016 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: dreibh@iem.uni-due.de
.\"
.\" ###### Setup ############################################################
.Dd April 20, 2012
.Dt fractgen 1
.Os fractgen
.\" ###### Name #############################################################
.Sh NAME
.Nm fractgen
.Nd Fractal Generator
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm fractgen
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm fractgen
 FractGen is a simple Qt-based fractal generator program for Mandelbrot
 fractals. The image size is only limited by virtual memory. It is possible
 to zoom into images. Image parameters can be saved in XML files and loaded
 from XML files. Calculated images can be exported as PNG files.
.br
 The intention of this program is to generate graphics to be post-processed
 by other image tools, e.g. in order to generate nice screen backgrounds or
 book covers.
.Pp
.\" ###### Authors ##########################################################
.Sh AUTHORS
Thomas Dreibholz
.br
http://www.iem.uni-due.de/~dreibh/fractalgenerator
.br
mailto://dreibh@iem.uni-due.de
.br
