#!/usr/bin/env bash

set -eu

ITERATIONS=5000
# RESOLUTION=1920x1080   # Full-HD
# RESOLUTION=3840x2160   # Ultra-HD 4K
RESOLUTION=7680x4320   # Ultra-HD 8K
FORMAT=webp

width="${RESOLUTION/x*/}"
height="${RESOLUTION/*x/}"
echo "Computing resolution ${width} x ${height}:"
find . -name "*.fsf" | \
   sed -e 's/\.fsf$//' | \
   xargs -I{} \
      clifractgen -W "${width}" -H "${height}" -M ${ITERATIONS} "{}.fsf" "{}-${width}x${height}.${FORMAT}"
