#!/usr/bin/env bash

set -eu

ITERATIONS=5000
WIDTH=1920
HEIGHT=1080
# WIDTH=3840
# HEIGHT=2160

find . -name "*.fsf" | \
   sed -e 's/\.fsf$//' | \
   xargs -I{} \
      clifractgen -W ${WIDTH} -H ${HEIGHT} -M ${ITERATIONS} {}.fsf {}.webp
