.\" Fractal Generator
.\" Copyright (C) 2003-2026 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: thomas.dreibholz@gmail.com
.\"
.\" ###### Setup ############################################################
.Dd May 11, 2026
.Dt clifractgen 1
.Os clifractgen
.\" ###### Name #############################################################
.Sh NAME
.Nm clifractgen
.Nd Fractal Generator
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm clifractgen Ar fsf\_file Ar output\_file
.br
.Op Fl W Ar image\_width | Fl Fl width Ar image\_width
.br
.Op Fl H Ar image\_height | Fl Fl height Ar image\_height
.br
.Op Fl M Ar max\_iterations | Fl Fl max-iterations Ar max\_iterations
.Nm clifractgen
.Op Fl h | Fl Fl help
.Nm clifractgen
.Op Fl v | Fl Fl version
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm clifractgen
is a simple Qt\-based fractal generator program for Mandelbrot fractals. The
image size is only limited by virtual memory. It is possible to zoom into
images. Image parameters can be saved in XML files and loaded from XML files.
Calculated images can be exported as PNG files. The intention of this program is
to generate graphics to be post\-processed by other image tools, e.g. in order
to generate nice screen backgrounds or book covers.
.br
This is the command\-line version of FractGen. This program can be used to
calculate files created by FractGen on machines without GUI, e.g. to produce
high\-resolution images on a powerful server.
.Pp
.\" ###### Exit status ######################################################
.Sh EXIT STATUS
The
.Nm
tool exits with 0 on success, and >0 in case of an error.
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following argument may be provided:
.Bl -tag -width indent
.It Ar fsf\_file
Specifies the input file.
.It Ar output\_file
Specifies the output file.
.It Fl W Ar image\_width | Fl Fl width Ar image\_width
Specifies the image width in pixels. Default: 1024.
.It Fl H Ar image\_height | Fl Fl height Ar image\_height
Specifies the image height in pixels. Default: 768.
.It Fl M Ar max\_iterations | Fl Fl max-iterations Ar max\_iterations
Specifies the maximum number of interations. Default: 250.
.It Fl h | Fl Fl help
Show arguments help and exit.
.It Fl v | Fl Fl version
Show version and exit.
.El
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It clifractgen \-h
.It clifractgen \-v
.It clifractgen fractgen.fsf fractgen\-uhd.png \-W 3840 \-H 2160 \-M 10000
.It clifractgen alpha05.fsf alpha05.png \-\-width 3840 \-\-height 2160 \-\-max\-iterations 10000
.It clifractgen beta07.fsf beta07\-A3.png \-W21000 \-H14850 \-M10000
.El
.\" ###### See also #########################################################
.Sh SEE ALSO
.Xr fractgen 1 ,
.Xr kfractgen 1
.\" ###### Notes ############################################################
.Sh NOTES
This program is part of FractGen. The latest version of FractGen can be found on the FractGen Homepage at
.Lk https://www.nntb.no/\(tidreibh/fractalgenerator/ "FractGen Homepage" .
.\" ###### Authors ##########################################################
.Sh AUTHORS
Thomas Dreibholz,
.Lk https://www.nntb.no/\(tidreibh "Homepage"
