.\" Fractal Generator
.\" Copyright (C) 2003-2026 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: thomas.dreibholz@gmail.com
.\"
.\" ###### Setup ############################################################
.Dd May 11, 2026
.Dt fractgen 1
.Os fractgen
.\" ###### Name #############################################################
.Sh NAME
.Nm fractgen
.Nd Fractal Generator
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm fractgen
.Op Ar fsf\_file Ar ...
.Nm fractgen
.Op Fl h | Fl Fl help
.Nm fractgen
.Op Fl v | Fl Fl version
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm fractgen
is a simple Qt\-based fractal generator program for Mandelbrot fractals. The image size is only limited by virtual memory. It is possible to zoom into images. Image parameters can be saved in XML files and loaded from XML files. Calculated images can be exported as PNG files.
.br
The intention of this program is to generate graphics to be post\-processed by other image tools, e.g. in order to generate nice screen backgrounds or book covers.
.br
This is the Qt version of FractGen.
.Pp
.\" ###### Exit status ######################################################
.Sh EXIT STATUS
The
.Nm
tool exits with 0 on success, and >0 in case of an error.
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following argument may be provided:
.Bl -tag -width indent
.It Ar fsf\_file Ar ...
Specifies input files to be loaded.
.It Fl h | Fl Fl help
Show arguments help and exit.
.It Fl v | Fl Fl version
Show version and exit.
.El
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It fractgen \-h
.It fractgen \-v
.It fractgen fractgen.fsf
.It fractgen beta01.fsf beta02.fsf beta03.fsf
.It fractgen examples/alpha*.fsf
.El
.\" ###### See also #########################################################
.Sh SEE ALSO
.Xr clifractgen 1 ,
.Xr kfractgen 1
.\" ###### Notes ############################################################
.Sh NOTES
This program is part of FractGen. The latest version of FractGen can be found on the FractGen Homepage at
.Lk https://www.nntb.no/\(tidreibh/fractalgenerator/ "FractGen Homepage" .
.\" ###### Authors ##########################################################
.Sh AUTHORS
Thomas Dreibholz,
.Lk https://www.nntb.no/\(tidreibh "Homepage"
