# Created by: Thomas Dreibholz <dreibh@iem.uni-due.de>
# $FreeBSD$

PORTNAME=	fractgen
PORTVERSION=	2.0.19
CATEGORIES=	graphics
MASTER_SITES=	https://www.uni-due.de/~be0001/fractalgenerator/download/

MAINTAINER=	dreibh@iem.uni-due.de
COMMENT=	Fractal Generator

LICENSE=	GPLv3

USES=		qmake
USE_QT5=        core qmake_build buildtools_build
QT_DIST=        base

.include <bsd.port.mk>
